services:
  app:
    image: hello
    ports:
      - 8000:8000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes: 
      - ~/mongo/:/data/db
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes: 
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9090"
  orion_server:
    image: pref
    ports:
      - 4200:4200
    volumes:
      - ~/pref/data:/data/pref
  agent:
    image: hello
    command: ./wait-for-it.sh orion_server:4200 -- poetry run prefect agent start -q default
